applicationconfiguration:
                        host: http://localhost
                        port: 8081
                        username: payment-dev-updated
                        password: payment-dev-updated
