applicationconfiguration:
                        host: http://localhost
                        port: 8081
                        username: payment-dev-updated-final
                        password: payment-dev-updated-final
